version: '3'

services:
  owncloud:
    image: harbor.tontron.com.cn/nas/tc-owncloud-docker
    tty: true
    ports:
    - 8080:80
    volumes:
    - /share/CACHEDEV1_DATA/cloudbacp:/var/www/html/data
  mysql:
    image: mariadb
    volumes:
      - /share/CACHEDEV1_DATA/owncloud/mysql:/var/lib/mysql
    command: [
            '--character-set-server=utf8',
            '--collation-server=utf8_general_ci',
            '--skip-name-resolve',
            '--default-time-zone=+8:00'
            ]
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: Tontron@1169#